# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a08e93c7ed6431745e109b159cc09f97d7fef7d6074508f00bd7e4742d6283078c2099d09e6fd817725cd6f7c036bc8d5e96c689cc34f360ccbedd03398d917b

test:
  secret_key_base: cad6e32df5589924b6a31c70d842395df51db89e37d47a2964a4ae68223b459a8d733b060dfc28eafe64436a856309a8686f950d69d5ffa5d64a731141bed673

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
